/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.isradice.ainf.forza4;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author arena
 */
public class GUI extends javax.swing.JFrame {

    private final ConnectFourGame game = new ConnectFourGame();
    private final JButton[] columnButtons = new JButton[ConnectFourGame.COLS];
    private final CellLabel[][] cellLabels = new CellLabel[ConnectFourGame.ROWS][ConnectFourGame.COLS];

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setTitle("Forza 4 - Connect Four");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        JPanel topPanel = new JPanel(new GridLayout(1, ConnectFourGame.COLS));
        for (int c = 0; c < ConnectFourGame.COLS; c++) {
            final int col = c;
            JButton btn = new JButton("↓");
            btn.setFont(new Font("SansSerif", Font.BOLD, 18));
            btn.addActionListener(e -> handleMove(col));
            columnButtons[col] = btn;
            topPanel.add(btn);
        }

        JPanel boardPanel = new JPanel(new GridLayout(ConnectFourGame.ROWS, ConnectFourGame.COLS));
        for (int r = 0; r < ConnectFourGame.ROWS; r++) {
            for (int c = 0; c < ConnectFourGame.COLS; c++) {
                cellLabels[r][c] = new CellLabel();
                boardPanel.add(cellLabels[r][c]);
            }
        }

        add(topPanel, BorderLayout.NORTH);
        add(boardPanel, BorderLayout.CENTER);

        setSize(700, 600);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
      private void handleMove(int col) {
        if (!game.dropDisc(col)) return;

        updateBoard();

        if (game.isGameOver()) {
            if (game.isDraw()) {
                JOptionPane.showMessageDialog(this, "It's a draw!");
            } else {
                String winner = (game.getWinner() == ConnectFourGame.CellColor.RED) ? "Red" : "Yellow";
                JOptionPane.showMessageDialog(this, winner + " wins!");
            }
            game.reset();
            updateBoard();
        }
    }

    private void updateBoard() {
        for (int r = 0; r < ConnectFourGame.ROWS; r++) {
            for (int c = 0; c < ConnectFourGame.COLS; c++) {
                cellLabels[r][c].setColor(game.getCell(r, c));
            }
        }
    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}


class CellLabel extends JLabel {
    public CellLabel() {
        setOpaque(true);
        setBorder(BorderFactory.createLineBorder(Color.BLACK));
        setBackground(Color.WHITE);
    }

    public void setColor(ConnectFourGame.CellColor color) {
        switch (color) {
            case RED -> setBackground(Color.RED);
            case YELLOW -> setBackground(Color.YELLOW);
            default -> setBackground(Color.WHITE);
        }
    }
}