package com.isradice.esercizioanagrafica;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author ykn18
 */
public class GUI extends javax.swing.JFrame {

    private ArrayList<Persona> arrPersone = new ArrayList<>();
    private String path;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        try (ObjectInputStream os = new ObjectInputStream(new FileInputStream("savefile"))){
            arrPersone = (ArrayList<Persona>) os.readObject();
        } catch(FileNotFoundException e){
            System.out.println("Save file not found");
        } catch (IOException e){
            System.out.println("Deserialize error");
        } catch (ClassNotFoundException e){
            System.out.println("Deserialize error");
        }
        ((CardLayout) this.getContentPane().getLayout()).show(this.getContentPane(), "cardHome");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileChooser = new javax.swing.JFileChooser();
        panelImporta = new javax.swing.JPanel();
        lblPath = new javax.swing.JLabel();
        btnPath = new javax.swing.JButton();
        btnImporta = new javax.swing.JButton();
        panelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelInserisci = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCognome = new javax.swing.JTextField();
        txtEta = new javax.swing.JTextField();
        btnInserisci = new javax.swing.JButton();
        panelVisualizza = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUtenti = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemInserisci = new javax.swing.JMenuItem();
        menuItemVisualizza = new javax.swing.JMenuItem();
        menuItemImporta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        lblPath.setText("Path:");

        btnPath.setText("Scegli file");
        btnPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPathActionPerformed(evt);
            }
        });

        btnImporta.setText("Importa");
        btnImporta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImportaLayout = new javax.swing.GroupLayout(panelImporta);
        panelImporta.setLayout(panelImportaLayout);
        panelImportaLayout.setHorizontalGroup(
            panelImportaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelImportaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImporta)
                    .addComponent(btnPath)
                    .addComponent(lblPath))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        panelImportaLayout.setVerticalGroup(
            panelImportaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblPath)
                .addGap(18, 18, 18)
                .addComponent(btnPath)
                .addGap(25, 25, 25)
                .addComponent(btnImporta)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        getContentPane().add(panelImporta, "cardImporta");

        jLabel1.setText("Benvenuti");

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        getContentPane().add(panelHome, "cardHome");

        panelInserisci.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Nome");
        panelInserisci.add(jLabel4, new java.awt.GridBagConstraints());

        jLabel5.setText("Cognome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelInserisci.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Età");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panelInserisci.add(jLabel6, gridBagConstraints);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelInserisci.add(txtNome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelInserisci.add(txtCognome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelInserisci.add(txtEta, gridBagConstraints);

        btnInserisci.setText("Inserisci");
        btnInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserisciActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        panelInserisci.add(btnInserisci, gridBagConstraints);

        getContentPane().add(panelInserisci, "cardInserisci");

        panelVisualizza.setLayout(new java.awt.GridBagLayout());

        txtUtenti.setColumns(20);
        txtUtenti.setRows(5);
        jScrollPane1.setViewportView(txtUtenti);

        panelVisualizza.add(jScrollPane1, new java.awt.GridBagConstraints());

        getContentPane().add(panelVisualizza, "cardVisualizza");

        jMenu1.setText("Opzioni");

        menuItemInserisci.setText("Inserisci");
        menuItemInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInserisciActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemInserisci);

        menuItemVisualizza.setText("Visualizza");
        menuItemVisualizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVisualizzaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemVisualizza);

        menuItemImporta.setText("Importa");
        menuItemImporta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemImportaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemImporta);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInserisciActionPerformed
        ((CardLayout) this.getContentPane().getLayout()).show(this.getContentPane(), "cardInserisci");
    }//GEN-LAST:event_menuItemInserisciActionPerformed

    private void menuItemVisualizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVisualizzaActionPerformed
        for(Persona p: arrPersone){
            txtUtenti.append(p.toString() + "\n");
        }
        ((CardLayout) this.getContentPane().getLayout()).show(this.getContentPane(), "cardVisualizza");
    }//GEN-LAST:event_menuItemVisualizzaActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserisciActionPerformed
        try{
            arrPersone.add(new Persona(txtNome.getText(), txtCognome.getText(), Integer.parseInt(txtEta.getText())));
            JOptionPane.showMessageDialog(this, "Utente inserito correttamente", "Inserimento riuscito", JOptionPane.INFORMATION_MESSAGE);
        } catch (EtaNonValidaException e){
            JOptionPane.showMessageDialog(this, "L'eta non può essere negativa", "Errore", JOptionPane.ERROR_MESSAGE);
        }
        
        clearFields();
        
        try (ObjectOutputStream os = new ObjectOutputStream(new FileOutputStream("savefile"))){
            os.writeObject(arrPersone);
        } catch(FileNotFoundException e){
            System.out.println("Save file not found");
        } catch (IOException e){
            System.out.println("Could not serialize file");
        } 
    }//GEN-LAST:event_btnInserisciActionPerformed

    private void btnPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPathActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            lblPath.setText("Path: " + file.getPath());
            path = file.getAbsolutePath();
        } else {
            System.out.println("Open command cancelled by user.");
        }
    }//GEN-LAST:event_btnPathActionPerformed

    private void menuItemImportaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemImportaActionPerformed
        ((CardLayout) this.getContentPane().getLayout()).show(this.getContentPane(), "cardImporta");
    }//GEN-LAST:event_menuItemImportaActionPerformed

    private void btnImportaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportaActionPerformed
        try(BufferedReader br = new BufferedReader(new FileReader(path))){
            String line;
            while((line = br.readLine()) != null){
                List<String> splitString = Arrays.asList(line.split(","));
                arrPersone.add(new Persona(splitString.get(0), splitString.get(1), Integer.parseInt(splitString.get(2))));
            }
        } catch (Exception e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_btnImportaActionPerformed

    private void clearFields(){
        txtNome.setText("");
        txtCognome.setText("");
        txtEta.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImporta;
    private javax.swing.JButton btnInserisci;
    private javax.swing.JButton btnPath;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPath;
    private javax.swing.JMenuItem menuItemImporta;
    private javax.swing.JMenuItem menuItemInserisci;
    private javax.swing.JMenuItem menuItemVisualizza;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelImporta;
    private javax.swing.JPanel panelInserisci;
    private javax.swing.JPanel panelVisualizza;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtEta;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtUtenti;
    // End of variables declaration//GEN-END:variables
}
