package com.isradice.esercizioscuolagui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;

/**
 *
 * @author ykn18
 */
public class GUI extends javax.swing.JFrame {

    private String tipoSelezionato = "Studente";
    private ArrayList<Utente> arrUtenti = new ArrayList<Utente>();
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(screenSize.width/4,screenSize.height/4,screenSize.width/4,screenSize.height/4);
        lblMateria.setVisible(false);
        txtMateria.setVisible(false);
        lblRuolo.setVisible(false);
        txtRuolo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        comboTipo = new javax.swing.JComboBox<>();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCognome = new javax.swing.JLabel();
        txtCognome = new javax.swing.JTextField();
        lblClasse = new javax.swing.JLabel();
        txtClasse = new javax.swing.JTextField();
        lblMateria = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        lblRuolo = new javax.swing.JLabel();
        txtRuolo = new javax.swing.JTextField();
        btnInserisci = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Studente", "Docente", "ATA" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });
        getContentPane().add(comboTipo, new java.awt.GridBagConstraints());

        lblNome.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 6);
        getContentPane().add(lblNome, gridBagConstraints);

        txtNome.setText(" ");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 6);
        getContentPane().add(txtNome, gridBagConstraints);

        lblCognome.setText("Cognome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 6);
        getContentPane().add(lblCognome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 6);
        getContentPane().add(txtCognome, gridBagConstraints);

        lblClasse.setText("Classe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 6);
        getContentPane().add(lblClasse, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 6);
        getContentPane().add(txtClasse, gridBagConstraints);

        lblMateria.setText("Materia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 6);
        getContentPane().add(lblMateria, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 6);
        getContentPane().add(txtMateria, gridBagConstraints);

        lblRuolo.setText("Ruolo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 6);
        getContentPane().add(lblRuolo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 6);
        getContentPane().add(txtRuolo, gridBagConstraints);

        btnInserisci.setText("Inserisci");
        btnInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserisciActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(btnInserisci, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        if((String)comboTipo.getSelectedItem() == "Studente"){
            lblClasse.setVisible(true);
            txtClasse.setVisible(true);
            lblMateria.setVisible(false);
            txtMateria.setVisible(false);
            lblRuolo.setVisible(false);
            txtRuolo.setVisible(false);
            tipoSelezionato = "Studente";
        } else if ((String)comboTipo.getSelectedItem() == "Docente"){
            lblClasse.setVisible(false);
            txtClasse.setVisible(false);
            lblMateria.setVisible(true);
            txtMateria.setVisible(true);
            lblRuolo.setVisible(false);
            txtRuolo.setVisible(false);
            tipoSelezionato = "Docente";
        } else if ((String)comboTipo.getSelectedItem() == "ATA") {
            lblClasse.setVisible(false);
            txtClasse.setVisible(false);
            lblMateria.setVisible(false);
            txtMateria.setVisible(false);
            lblRuolo.setVisible(true);
            txtRuolo.setVisible(true);
            tipoSelezionato = "ATA";
        }
    }//GEN-LAST:event_comboTipoActionPerformed

    private void btnInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserisciActionPerformed
        if(tipoSelezionato == "Studente") {
            Studente s = new Studente(txtClasse.getText(), txtNome.getText(), txtCognome.getText());
            arrUtenti.add(s);
        } else if (tipoSelezionato == "Docente"){
            Docente d = new Docente(txtMateria.getText(), txtNome.getText(), txtCognome.getText());
            arrUtenti.add(d);
        } else if (tipoSelezionato == "ATA") {
            ATA a = new ATA(txtRuolo.getText(), txtNome.getText(), txtCognome.getText());
            arrUtenti.add(a);
        }
        
        for(Utente u : arrUtenti){
            System.out.println(u.getNominativo());
        }
    }//GEN-LAST:event_btnInserisciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnInserisci;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel lblClasse;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRuolo;
    private javax.swing.JTextField txtClasse;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRuolo;
    // End of variables declaration//GEN-END:variables
}
