package com.isradice.eserciziointerfacce;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;

/**
 *
 * @author ykn18
 */
public class GUI extends javax.swing.JFrame {

    final private String defaultText = "";
    private String selectedType = "CD";
    private String albumName;
    private int year;
    private int capacity;
    private int diameter;
    private ArrayList<Media> albums;
    /**
     * Creates new form MyWindow
     */
    public GUI() {  
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(screenSize.width/4,screenSize.height/4,screenSize.width/4,screenSize.height/4);
        labelDiameter.setVisible(false);
        textDiameter.setVisible(false);
        albums = new ArrayList<Media>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSpinner1 = new javax.swing.JSpinner();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textYear = new javax.swing.JTextField();
        textAlbumName = new javax.swing.JTextField();
        radioCD = new javax.swing.JRadioButton();
        radioVinil = new javax.swing.JRadioButton();
        labelCapacity = new javax.swing.JLabel();
        textDiameter = new javax.swing.JTextField();
        labelDiameter = new javax.swing.JLabel();
        textCapacity = new javax.swing.JTextField();
        insertBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+2f));
        jLabel1.setText("Nome Album");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 17, 5, 5);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+2f));
        jLabel2.setText("Anno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 17, 5, 5);
        jPanel2.add(jLabel2, gridBagConstraints);

        textYear.setFont(textYear.getFont().deriveFont(textYear.getFont().getSize()+2f));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 17, 5, 5);
        jPanel2.add(textYear, gridBagConstraints);

        textAlbumName.setFont(textAlbumName.getFont().deriveFont(textAlbumName.getFont().getSize()+2f));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 17, 5, 5);
        jPanel2.add(textAlbumName, gridBagConstraints);

        buttonGroup1.add(radioCD);
        radioCD.setFont(radioCD.getFont().deriveFont(radioCD.getFont().getSize()+2f));
        radioCD.setSelected(true);
        radioCD.setLabel("CD");
        radioCD.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioCDStateChanged(evt);
            }
        });
        radioCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 17, 5, 5);
        jPanel2.add(radioCD, gridBagConstraints);

        buttonGroup1.add(radioVinil);
        radioVinil.setFont(radioVinil.getFont().deriveFont(radioVinil.getFont().getSize()+2f));
        radioVinil.setLabel("Vinile");
        radioVinil.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioVinilStateChanged(evt);
            }
        });
        radioVinil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVinilActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 17, 5, 5);
        jPanel2.add(radioVinil, gridBagConstraints);

        labelCapacity.setFont(labelCapacity.getFont().deriveFont(labelCapacity.getFont().getSize()+2f));
        labelCapacity.setText("Capacità");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 17, 5, 5);
        jPanel2.add(labelCapacity, gridBagConstraints);

        textDiameter.setFont(textDiameter.getFont().deriveFont(textDiameter.getFont().getSize()+2f));
        textDiameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDiameterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 17, 5, 5);
        jPanel2.add(textDiameter, gridBagConstraints);

        labelDiameter.setFont(labelDiameter.getFont().deriveFont(labelDiameter.getFont().getSize()+2f));
        labelDiameter.setText("Diametro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 17, 5, 5);
        jPanel2.add(labelDiameter, gridBagConstraints);

        textCapacity.setFont(textCapacity.getFont().deriveFont(textCapacity.getFont().getSize()+2f));
        textCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCapacityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 17, 5, 5);
        jPanel2.add(textCapacity, gridBagConstraints);

        insertBtn.setText("Inserisci album");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(8, 17, 5, 5);
        jPanel2.add(insertBtn, gridBagConstraints);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCDActionPerformed

    private void textDiameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDiameterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDiameterActionPerformed

    private void textCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCapacityActionPerformed

    private void radioVinilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVinilActionPerformed
        
    }//GEN-LAST:event_radioVinilActionPerformed

    private void radioCDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioCDStateChanged
        if(radioCD.isSelected()) {
            selectedType = "CD";
            textCapacity.setVisible(true);
            labelCapacity.setVisible(true);
            textDiameter.setVisible(false);
            labelDiameter.setVisible(false);
        } else {
            selectedType = "Vinile";
            textCapacity.setVisible(false);
            labelCapacity.setVisible(false);
            textDiameter.setVisible(true);
            labelDiameter.setVisible(true);
        }
    }//GEN-LAST:event_radioCDStateChanged

    private void radioVinilStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioVinilStateChanged
        
    }//GEN-LAST:event_radioVinilStateChanged

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        albumName = textAlbumName.getText();
        year = Integer.parseInt(textYear.getText());
        
        switch(selectedType){
            case "CD":
                capacity = Integer.parseInt(textCapacity.getText());
                CD c = new CD(capacity, year, albumName);
                albums.add(c);
                break;
            case "Vinile":
                diameter = Integer.parseInt(textDiameter.getText());
                Vinile v = new Vinile(diameter, year, albumName);   
                albums.add(v);
                break;
        }
        System.out.println(albums);  
        clear();
    }//GEN-LAST:event_insertBtnActionPerformed

    private void clear(){
        textAlbumName.setText(defaultText);
        textYear.setText(defaultText);
        textCapacity.setText(defaultText);
        textDiameter.setText(defaultText);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel labelCapacity;
    private javax.swing.JLabel labelDiameter;
    private javax.swing.JRadioButton radioCD;
    private javax.swing.JRadioButton radioVinil;
    private javax.swing.JTextField textAlbumName;
    private javax.swing.JTextField textCapacity;
    private javax.swing.JTextField textDiameter;
    private javax.swing.JTextField textYear;
    // End of variables declaration//GEN-END:variables
}
