package com.isradice.magazzinobrico;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/**
 *
 * @author ykn18
 */
public class GUI extends javax.swing.JFrame {
    final String CARTA_DA_PARATI_NOME = "Carta da parati";
    final String VERNICE_NOME = "Vernice";
    final String PIASTRELLA_NOME = "Piastrella";
    
    ArrayList<Prodotto> arrProdotti = new ArrayList<>();
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        comboTipo.addItem(VERNICE_NOME);
        comboTipo.addItem(CARTA_DA_PARATI_NOME);
        comboTipo.addItem(PIASTRELLA_NOME);
                
        try (ObjectInputStream os = new ObjectInputStream(new FileInputStream("savefile"))){
            arrProdotti = (ArrayList<Prodotto>) os.readObject();
        } catch(FileNotFoundException e){
            System.out.println("Save file not found");
        } catch (IOException e){
            System.out.println("Deserialize error");
        } catch (ClassNotFoundException e){
            System.out.println("Deserialize error");
        }
        drawInterface();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        comboTipo = new javax.swing.JComboBox<>();
        lblNome = new javax.swing.JLabel();
        lblPrezzo = new javax.swing.JLabel();
        lblForma = new javax.swing.JLabel();
        lblAltezza = new javax.swing.JLabel();
        lblLarghezza = new javax.swing.JLabel();
        lblMetri = new javax.swing.JLabel();
        lblDescrizione = new javax.swing.JLabel();
        lblColore = new javax.swing.JLabel();
        lblLitri = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPrezzo = new javax.swing.JTextField();
        txtAltezza = new javax.swing.JTextField();
        txtLarghezza = new javax.swing.JTextField();
        txtMetri = new javax.swing.JTextField();
        txtDescrizione = new javax.swing.JTextField();
        txtColore = new javax.swing.JTextField();
        txtLitri = new javax.swing.JTextField();
        comboForma = new javax.swing.JComboBox<>();
        btnInserisci = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });
        getContentPane().add(comboTipo, new java.awt.GridBagConstraints());

        lblNome.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(lblNome, gridBagConstraints);

        lblPrezzo.setText("Prezzo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(lblPrezzo, gridBagConstraints);

        lblForma.setText("Forma");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(lblForma, gridBagConstraints);

        lblAltezza.setText("Altezza");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(lblAltezza, gridBagConstraints);

        lblLarghezza.setText("Larghezza");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        getContentPane().add(lblLarghezza, gridBagConstraints);

        lblMetri.setText("Metri");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        getContentPane().add(lblMetri, gridBagConstraints);

        lblDescrizione.setText("Descrizione");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        getContentPane().add(lblDescrizione, gridBagConstraints);

        lblColore.setText("Colore");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        getContentPane().add(lblColore, gridBagConstraints);

        lblLitri.setText("Litri");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        getContentPane().add(lblLitri, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(txtNome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(txtPrezzo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(txtAltezza, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(txtLarghezza, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(txtMetri, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(txtDescrizione, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(txtColore, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(txtLitri, gridBagConstraints);

        comboForma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quadrata", "Rettangolare", "Esagonale" }));
        comboForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFormaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(comboForma, gridBagConstraints);

        btnInserisci.setText("Inserisci");
        btnInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserisciActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(btnInserisci, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        drawInterface();
    }//GEN-LAST:event_comboTipoActionPerformed

    private void btnInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserisciActionPerformed
        try{
            switch((String)comboTipo.getSelectedItem()){
                case CARTA_DA_PARATI_NOME:
                    CartaParati c = new CartaParati(txtDescrizione.getText(), Integer.parseInt(txtMetri.getText()), txtNome.getText(), Double.parseDouble(txtPrezzo.getText()));
                    arrProdotti.add(c);
                    break;
                case VERNICE_NOME:
                    Vernice v = new Vernice(txtColore.getText(), Integer.parseInt(txtLitri.getText()), txtNome.getText(), Double.parseDouble(txtPrezzo.getText()));
                    arrProdotti.add(v);
                    break;
                case PIASTRELLA_NOME:
                    TipoForma t = null;
                    if ((String)comboForma.getSelectedItem() == "Quadrata"){
                        t = TipoForma.Quadrata;
                    } else if ((String)comboForma.getSelectedItem() == "Rettangolare"){
                        t = TipoForma.Rettangolare;
                    } else if ((String)comboForma.getSelectedItem() == "Esagonale"){
                        t = TipoForma.Esagonale;
                    }
                    
                    Piastrella p = new Piastrella(t, Double.parseDouble(txtAltezza.getText()), Double.parseDouble(txtLarghezza.getText()), txtNome.getText(), Double.parseDouble(txtPrezzo.getText()));
                    arrProdotti.add(p);
                    break;
            }
        } catch (PrezzoNonValidoException e){
            System.out.println("Prezzo non valido");
        }
        
        cleanupInterface();
        System.out.println(arrProdotti);
        
        try (ObjectOutputStream os = new ObjectOutputStream(new FileOutputStream("savefile"))){
            os.writeObject(arrProdotti);
        } catch(FileNotFoundException e){
            System.out.println("Save file not found");
        } catch (IOException e){
            System.out.println("Could not serialize file");
        } 
    }//GEN-LAST:event_btnInserisciActionPerformed

    private void comboFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFormaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFormaActionPerformed

    private void drawInterface(){
        lblForma.setVisible(comboTipo.getSelectedItem() == PIASTRELLA_NOME);
        lblAltezza.setVisible(comboTipo.getSelectedItem() == PIASTRELLA_NOME);
        lblLarghezza.setVisible(comboTipo.getSelectedItem() == PIASTRELLA_NOME);
        lblMetri.setVisible(comboTipo.getSelectedItem() == CARTA_DA_PARATI_NOME);
        lblDescrizione.setVisible(comboTipo.getSelectedItem() == CARTA_DA_PARATI_NOME);
        lblColore.setVisible(comboTipo.getSelectedItem() == VERNICE_NOME);
        lblLitri.setVisible(comboTipo.getSelectedItem() == VERNICE_NOME);
        
        comboForma.setVisible(comboTipo.getSelectedItem() == PIASTRELLA_NOME);
        txtAltezza.setVisible(comboTipo.getSelectedItem() == PIASTRELLA_NOME);
        txtLarghezza.setVisible(comboTipo.getSelectedItem() == PIASTRELLA_NOME);
        txtMetri.setVisible(comboTipo.getSelectedItem() == CARTA_DA_PARATI_NOME);
        txtDescrizione.setVisible(comboTipo.getSelectedItem() == CARTA_DA_PARATI_NOME);
        txtColore.setVisible(comboTipo.getSelectedItem() == VERNICE_NOME);
        txtLitri.setVisible(comboTipo.getSelectedItem() == VERNICE_NOME);
    }
    
    private void cleanupInterface(){
        txtAltezza.setText("");
        txtLarghezza.setText("");
        txtMetri.setText("");
        txtDescrizione.setText("");
        txtColore.setText("");
        txtLitri.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserisci;
    private javax.swing.JComboBox<String> comboForma;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAltezza;
    private javax.swing.JLabel lblColore;
    private javax.swing.JLabel lblDescrizione;
    private javax.swing.JLabel lblForma;
    private javax.swing.JLabel lblLarghezza;
    private javax.swing.JLabel lblLitri;
    private javax.swing.JLabel lblMetri;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPrezzo;
    private javax.swing.JTextField txtAltezza;
    private javax.swing.JTextField txtColore;
    private javax.swing.JTextField txtDescrizione;
    private javax.swing.JTextField txtLarghezza;
    private javax.swing.JTextField txtLitri;
    private javax.swing.JTextField txtMetri;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPrezzo;
    // End of variables declaration//GEN-END:variables
}
